# Generated by Django 6.0.7 on 2026-08-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_admin_add_college_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_add_college',
            name='college_types',
            field=models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('GOVERNMENT', 'GOVERNMENT')], default='PRIVATE', max_length=100),
            preserve_default=False,
        ),
    ]
