# Generated by Django 6.0.7 on 2026-08-23 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_academicyearsemester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_duration', models.CharField(choices=[('1 Years', '1 Years'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_course', to='adminpanel.admin_add_college')),
            ],
        ),
    ]
