# Generated by Django 6.0.7 on 2026-08-23 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='college',
        ),
    ]
