# Generated by Django 6.0.7 on 2026-08-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_remove_courses_college'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='AdminCourses',
        ),
    ]
