# Generated by Django 6.0.7 on 2026-08-29 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_rename_courses_admincourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='addSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('paper_code', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.admincourses')),
                ('year_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.academicyearsemester')),
            ],
        ),
    ]
