# Generated by Django 6.0.7 on 2026-08-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_addsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsubject',
            name='paper_choice',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor')], default='major', max_length=10),
        ),
        migrations.AddField(
            model_name='addsubject',
            name='subject_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], default='theory', max_length=10),
        ),
    ]
