# Generated by Django 6.0.7 on 2026-09-01 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_addsubject_paper_choice_addsubject_subject_type'),
        ('college', '0010_add_subject_teacher_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('student_added', 'Student Added'), ('teacher_added', 'Teacher Added'), ('student_updated', 'Student Updated'), ('teacher_updated', 'Teacher Updated'), ('subject_teacher_added', 'Subject Teacher Added')], max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='adminpanel.admin_add_college')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='college.addstudent')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='college.addteacher')),
            ],
        ),
    ]
