# Generated by Django 6.0.7 on 2026-09-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_notification'),
        ('college', '0010_add_subject_teacher_combination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='UniversityNotification',
        ),
    ]
