# Generated by Django 6.0.7 on 2026-09-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_adminnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitynotification',
            name='notification_type',
            field=models.CharField(choices=[('student_added', 'Student Added'), ('teacher_added', 'Teacher Added'), ('student_updated', 'Student Updated'), ('teacher_updated', 'Teacher Updated'), ('subject_teacher_added', 'Subject Teacher Added'), ('ca1_added', 'CA1_Added'), ('ca2_added', 'CA2_Added'), ('ca3_added', 'CA3_Added')], max_length=50),
        ),
    ]
