# Generated by Django 6.0.7 on 2026-09-15 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_alter_universitynotification_notification_type'),
        ('college', '0014_pca_marks_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardNumber', models.CharField(max_length=100)),
                ('ExamDate', models.DateField()),
                ('GeneratedAt', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Exam_Type', models.CharField(choices=[('Even', 'Even'), ('Odd', 'Odd')], max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentAdmitCard', to='college.addstudent')),
            ],
        ),
    ]
