# Generated by Django 6.0.7 on 2026-09-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_admitcard'),
        ('college', '0014_pca_marks_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitCardGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards_Generate', to='adminpanel.admin_add_college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards_Generate', to='college.collegecourses')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='adminpanel.academicyearsemester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='adminpanel.addsubject')),
            ],
        ),
    ]
