# Generated by Django 6.0.7 on 2026-09-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_admitcardgenerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitcardgenerate',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='admitcardgenerate',
            name='exam_time',
        ),
        migrations.RemoveField(
            model_name='admitcardgenerate',
            name='subject',
        ),
        migrations.AddField(
            model_name='admitcardgenerate',
            name='subject_date_time',
            field=models.JSONField(default=dict),
        ),
    ]
