# Generated by Django 6.0.7 on 2026-09-30 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_remove_admitcardgenerate_exam_date_and_more'),
        ('college', '0016_rename_subjects_universityexammarks_subjects_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('ca_marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.camarks')),
                ('pca_marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.pca_marks')),
                ('written_marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.universityexammarks')),
            ],
        ),
    ]
