# Generated by Django 6.0.7 on 2026-08-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0002_admin_add_college_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('college_logo', models.ImageField(blank=True, null=True, upload_to='college_logo/')),
                ('website', models.URLField(blank=True, null=True)),
                ('director_name', models.CharField(blank=True, max_length=150)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.admin_add_college')),
            ],
        ),
    ]
