# Generated by Django 6.0.7 on 2026-08-22 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_admin_add_college_college_types'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeprofile',
            name='college',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_profile', to='adminpanel.admin_add_college'),
        ),
    ]
