# Generated by Django 6.0.7 on 2026-08-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_admin_add_college_college_types'),
        ('college', '0003_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='college',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='college_course', to='adminpanel.admin_add_college'),
            preserve_default=False,
        ),
    ]
