# Generated by Django 6.0.7 on 2026-08-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_courses_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(choices=[('1 Years', '1 Years'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years')], max_length=10),
        ),
    ]
