# Generated by Django 6.0.7 on 2026-08-23 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_courses'),
        ('college', '0005_alter_courses_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.admin_add_college'),
        ),
    ]
