# Generated by Django 6.0.7 on 2026-08-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_rename_courses_admincourses'),
        ('college', '0006_alter_courses_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.admin_add_college')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.admincourses')),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
