# Generated by Django 6.0.7 on 2026-08-24 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_rename_courses_admincourses'),
        ('college', '0007_collegecourses_delete_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('admission_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('college_verify', models.BooleanField(default=True)),
                ('university_verify', models.BooleanField(default=False)),
                ('roll_number', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=250)),
                ('college_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_details', to='college.collegecourses')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.academicyearsemester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
