# Generated by Django 6.0.7 on 2026-08-31 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_addsubject_paper_choice_addsubject_subject_type'),
        ('college', '0009_addteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_subject_teacher_combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_course_details', to='college.collegecourses')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.academicyearsemester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.addsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.addteacher')),
            ],
        ),
    ]
