# Generated by Django 6.0.7 on 2026-09-04 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_add_subject_teacher_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_type', models.CharField(choices=[('CA1', 'CA1'), ('CA2', 'CA2'), ('CA3', 'CA3')], max_length=100)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('crated_at', models.DateField(auto_now_add=True)),
                ('college_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.addstudent')),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.add_subject_teacher_combination')),
            ],
        ),
    ]
