# Generated by Django 6.0.7 on 2026-09-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_alter_universitynotification_notification_type'),
        ('college', '0011_camarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCA_Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_marks', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pca_marks', to='college.collegecourses')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.academicyearsemester')),
            ],
        ),
    ]
