# Generated by Django 6.0.7 on 2026-09-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_alter_universitynotification_notification_type'),
        ('college', '0012_pca_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegecourses',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collegecourses', to='adminpanel.admincourses'),
        ),
    ]
