# Generated by Django 6.0.7 on 2026-09-11 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_alter_collegecourses_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca_marks',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.addstudent'),
            preserve_default=False,
        ),
    ]
