# Generated by Django 6.0.7 on 2026-09-24 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_pca_marks_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityExamMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.JSONField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.addstudent')),
            ],
        ),
    ]
