# Generated by Django 6.0.7 on 2026-09-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_universityexammarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityexammarks',
            old_name='subjects',
            new_name='subjects_marks',
        ),
    ]
