# Generated by Django 6.0.7 on 2026-09-20 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0016_remove_admitcardgenerate_exam_date_and_more'),
        ('college', '0014_pca_marks_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_photo', models.ImageField(upload_to='studentPhoto/')),
                ('student_signature', models.ImageField(upload_to='studentSignature/')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.admin_add_college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.addstudent')),
            ],
        ),
    ]
