# Generated by Django 6.0.7 on 2026-09-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo_signature',
            old_name='college_id',
            new_name='college',
        ),
    ]
